### ISSUE TITLE
android64 - game crashes when opening editor

### ISSUE THREAD

**Issue by Kingminer7** [Alphalaneous/Editor-Sounds#1]
android64 - game crashes when i open the editor
[Crash_2024-06-16_08.57.07.dmp.txt](https://github.com/user-attachments/files/15858220/Crash_2024-06-16_08.57.07.dmp.txt)
[Crash_2024-06-16_08.52.08.dmp.txt](https://github.com/user-attachments/files/15858221/Crash_2024-06-16_08.52.08.dmp.txt)

**Comment by Alphalaneous** [comment]
Fixed in 1.1.1
