### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Denyscrasav4ik** [Alphalaneous/Editor-Sounds#2]
Any gray button in the pause menu of editor will crash the game

Im mobile

### Crashlog go here:
[Crash 2024-06-23 09.37.23.dmp](https://github.com/user-attachments/files/15942838/Crash.2024-06-23.09.37.23.dmp)

**Comment by Alphalaneous** [comment]
Can you send a list of mods you have as well?

**Comment by Denyscrasav4ik** [comment]
Godlike faces,

**Comment by Denyscrasav4ik** [comment]
Godlije faces, ingamelistmod, editor sounds, ez clipboard, happy textures, is it sent?, pages api, projected stars, random tab, transparent lists, gddl integration, click sounds, clean startpos, icon profile, menu shader, smooth particles, better info, compact lists, misc bugfixes, globed, copy song id, death tracker, golden best, auto nong, jukebox, gdutils, node ids, texrure loader, better icon randmizer, demons in-between, integrated demon list, level size, more object info, n/a demon, gmd api, better progression, profile rankings, grandpa demon, badges api, mod profiles, level info, run info, better song preview, gddp integrarion, shopping list, treasure checklist, garage in editor, ids integration, nlw integration, garage plus, mini next free, better unlock info, minecraft splash, gd roulette, gradient pages, qolmod, more difficulties, texture workshop, high graphics on android, level info in pause menu, objects with ldm, restart buttons, super expert, youtubers, xxlify, xdbot (not on workshop), click between steps.

**Comment by Denyscrasav4ik** [comment]
Also i checked its not every gray button its only the select and aligh buttons

**Comment by Alphalaneous** [comment]
This should be resolved now, closing
